---
name: pre_merge_build

run-name: ${{ github.event.pull_request.number && 'Pre Merge Build PR:' || 'Pre Merge Build:' }}${{ github.event.pull_request.number || github.run_number }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: Audioreach/audioreach-workflows/.github/workflows/loading.yml@master
    with:
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  build:
    needs: load_parameters
    uses: Audioreach/audioreach-workflows/.github/workflows/build.yml@master
    secrets: inherit
    with:
      build_args: ${{ needs.load_parameters.outputs.build_args }}
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      event_name: ${{ github.event_name }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  process_image:
    needs: [load_parameters, build]
    uses: Audioreach/audioreach-workflows/.github/workflows/process_image.yml@master
    secrets: inherit
    with:
      event_name: ${{ github.event_name }}
      build_matrix: ${{ needs.load_parameters.outputs.build_matrix }}
      pr_ref: ${{ github.event.pull_request.head.ref }}
      pr_repo: ${{ github.event.pull_request.head.repo.full_name }}

  filter_test_matrix:
    needs: load_parameters
    runs-on: ubuntu-latest
    outputs:
      test_matrix: ${{ steps.filter.outputs.test_matrix }}
    steps:
      - id: filter
        shell: bash
        run: |
          MATRIX='${{ needs.load_parameters.outputs.build_matrix }}'

          echo "$MATRIX" | jq . >/dev/null

          FILTERED=$(echo "$MATRIX" | jq -c '
            if type == "object" then
              to_entries
              | map(select(.value.testing_enabled == true))
              | from_entries
            elif type == "array" then
              map(select(.testing_enabled == true))
            else
              error("Unsupported JSON type")
            end
          ')

          echo "$FILTERED" > test_matrix.json
          echo "test_matrix=$FILTERED" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: test-matrix
          path: test_matrix.json
